# Generated by Django 3.1.4 on 2020-12-24 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('IND', 'India'), ('USA', 'America'), ('PAK', 'Pakistan'), ('SA', 'South_africa')], default='IND', max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
